# Generated by Django 4.2.1 on 2023-06-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_chead1_blogpost_chead2_alter_blogpost_head0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='chead1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head2',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
