# Generated by Django 4.2.1 on 2023-05-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items_json',
            new_name='items_Json',
        ),
    ]
